FROM adoptopenjdk:11-jdk-hotspot
ADD build/libs/petree-0.0.1-SNAPSHOT.jar app.jar
#ADD src/main/resources/application-prod.yml app/application-prod.yml (이미 jar안에 명시되기때문에 포함시킬 필요없음)
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=prod","/app.jar"]