# application-dev.yml
server:
  port: '8010'

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: true
  #redis
  redis:
    host: localhost
    port: 6379

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
            BasicBinder: TRACE
